hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: uploadDir/postScript.sh
      timeout: 300
      runas: ubuntu
